export const SET_WORK_FILTER = 'SET_WORK_FILTER';
export const TOGGLE_MOBILE_MENU_VIS = 'TOGGLE_MOBILE_MENU_VIS';
export const SET_MOBILE_MENU_VIS = 'SET_MOBILE_MENU_VIS';
export const SET_CLEAR_OF_HEADER = 'SET_CLEAR_OF_HEADER';
